namespace Algorithms.LeetCode
{
    /* 389. Find the Difference
     * 
     * Given two strings s and t which consist of only lowercase letters.
     * 
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * 
     * Find the letter that was added in t.
     * 
     * Example:
     * 
     * Input:
     * s = "abcd"
     * t = "abcde"
     * 
     * Output:
     * e
     * 
     * Explanation:
     * 'e' is the letter that was added.
     */
    public class FindTheDifferenceSolution
    {
        public char FindTheDifference(string s, string t)
        {
            // Same as "Problem 136. Single Number".
            int result = 0;
            foreach (char c in s)
            {
                result = result ^ c;
            }

            foreach (char c in t)
            {
                result = result ^ c;
            }

            return (char)result;
        }
    }
}
